github_token: ${{ secrets.JAVA_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-buildpacks"

package:
  repository:     gcr.io/paketo-buildpacks/gradle
  register:       true
  registry_token: ${{ secrets.JAVA_BUILDPACK_REGISTRY_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.JAVA_GCLOUD_SERVICE_ACCOUNT_KEY }}

dependencies:
- id:   gradle
  uses: docker://ghcr.io/paketo-buildpacks/actions/gradle-dependency:main
